In [1]:
# -*- coding: utf-8 -*-
import os
import pandas as pd
from opencage.geocoder import OpenCageGeocode

In [2]:
opencagekey = open('key.secret','r')
key = opencagekey.read().replace('\n', '')
opencagekey.close()

In [3]:
dataset = pd.read_csv('caso_full.csv')

In [4]:
print(dataset[0:15])

          city  city_ibge_code        date  epidemiological_week  \
0   Rio Branco       1200401.0  2020-03-17                202012
1          NaN            12.0  2020-03-17                202012
2   Rio Branco       1200401.0  2020-03-18                202012
3          NaN            12.0  2020-03-18                202012
4   Rio Branco       1200401.0  2020-03-19                202012
5          NaN            12.0  2020-03-19                202012
6   Rio Branco       1200401.0  2020-03-20                202012
7          NaN            12.0  2020-03-20                202012
8   Rio Branco       1200401.0  2020-03-21                202012
9          NaN            12.0  2020-03-21                202012
10  Rio Branco       1200401.0  2020-03-22                202013
11         NaN            12.0  2020-03-22                202013
12  Rio Branco       1200401.0  2020-03-23                202013
13         NaN            12.0  2020-03-23                202013
14  Rio Branco       1200401.0  2020-03-24                202013

    estimated_population  estimated_population_2019  is_last  is_repeated  \
0               413418.0                   407319.0    False        False
1               894470.0                   881935.0    False        False
2               413418.0                   407319.0    False        False
3               894470.0                   881935.0    False        False
4               413418.0                   407319.0    False        False
5               894470.0                   881935.0    False        False
6               413418.0                   407319.0    False        False
7               894470.0                   881935.0    False        False
8               413418.0                   407319.0    False        False
9               894470.0                   881935.0    False        False
10              413418.0                   407319.0    False        False
11              894470.0                   881935.0    False        False
12              413418.0                   407319.0    False        False
13              894470.0                   881935.0    False        False
14              413418.0                   407319.0    False        False

    last_available_confirmed  last_available_confirmed_per_100k_inhabitants  \
0                          3                                        0.72566
1                          3                                        0.33539
2                          3                                        0.72566
3                          3                                        0.33539
4                          4                                        0.96754
5                          4                                        0.44719
6                          7                                        1.69320
7                          7                                        0.78259
8                         11                                        2.66075
9                         11                                        1.22978
10                        11                                        2.66075
11                        11                                        1.22978
12                        17                                        4.11206
13                        17                                        1.90057
14                        21                                        5.07960

   last_available_date  last_available_death_rate  last_available_deaths  \
0           2020-03-17                        0.0                      0
1           2020-03-17                        0.0                      0
2           2020-03-18                        0.0                      0
3           2020-03-18                        0.0                      0
4           2020-03-19                        0.0                      0
5           2020-03-19                        0.0                      0
6           2020-03-20                        0.0                      0
7           2020-03-20                        0.0                      0
8           2020-03-21                        0.0                      0
9           2020-03-21                        0.0                      0
10          2020-03-22                        0.0                      0
11          2020-03-22                        0.0                      0
12          2020-03-23                        0.0                      0
13          2020-03-23                        0.0                      0
14          2020-03-24                        0.0                      0

    order_for_place place_type state  new_confirmed  new_deaths
0                 1       city    AC              3           0
1                 1      state    AC              3           0
2                 2       city    AC              0           0
3                 2      state    AC              0           0
4                 3       city    AC              1           0
5                 3      state    AC              1           0
6                 4       city    AC              3           0
7                 4      state    AC              3           0
8                 5       city    AC              4           0
9                 5      state    AC              4           0
10                6       city    AC              0           0
11                6      state    AC              0           0
12                7       city    AC              6           0
13                7      state    AC              6           0
14                8       city    AC              4           0

In [5]:
dataset = pd.read_csv('caso_full.csv', encoding= 'utf-8', usecols = [
    'city',
    'city_ibge_code',
    'date',
    'epidemiological_week',
    'estimated_population',
    'last_available_confirmed',
    'last_available_confirmed_per_100k_inhabitants',
    'last_available_deaths',
    'place_type',
    'state',
    'new_confirmed',
    'new_deaths'                                                                      
])

In [6]:
print(dataset[0:15])

          city  city_ibge_code        date  epidemiological_week  \
0   Rio Branco       1200401.0  2020-03-17                202012
1          NaN            12.0  2020-03-17                202012
2   Rio Branco       1200401.0  2020-03-18                202012
3          NaN            12.0  2020-03-18                202012
4   Rio Branco       1200401.0  2020-03-19                202012
5          NaN            12.0  2020-03-19                202012
6   Rio Branco       1200401.0  2020-03-20                202012
7          NaN            12.0  2020-03-20                202012
8   Rio Branco       1200401.0  2020-03-21                202012
9          NaN            12.0  2020-03-21                202012
10  Rio Branco       1200401.0  2020-03-22                202013
11         NaN            12.0  2020-03-22                202013
12  Rio Branco       1200401.0  2020-03-23                202013
13         NaN            12.0  2020-03-23                202013
14  Rio Branco       1200401.0  2020-03-24                202013

    estimated_population  last_available_confirmed  \
0               413418.0                         3
1               894470.0                         3
2               413418.0                         3
3               894470.0                         3
4               413418.0                         4
5               894470.0                         4
6               413418.0                         7
7               894470.0                         7
8               413418.0                        11
9               894470.0                        11
10              413418.0                        11
11              894470.0                        11
12              413418.0                        17
13              894470.0                        17
14              413418.0                        21

    last_available_confirmed_per_100k_inhabitants  last_available_deaths  \
0                                         0.72566                      0
1                                         0.33539                      0
2                                         0.72566                      0
3                                         0.33539                      0
4                                         0.96754                      0
5                                         0.44719                      0
6                                         1.69320                      0
7                                         0.78259                      0
8                                         2.66075                      0
9                                         1.22978                      0
10                                        2.66075                      0
11                                        1.22978                      0
12                                        4.11206                      0
13                                        1.90057                      0
14                                        5.07960                      0

   place_type state  new_confirmed  new_deaths
0        city    AC              3           0
1       state    AC              3           0
2        city    AC              0           0
3       state    AC              0           0
4        city    AC              1           0
5       state    AC              1           0
6        city    AC              3           0
7       state    AC              3           0
8        city    AC              4           0
9       state    AC              4           0
10       city    AC              0           0
11      state    AC              0           0
12       city    AC              6           0
13      state    AC              6           0
14       city    AC              4           0

In [7]:
dataset = dataset.rename(columns = {
    'city':'muni',
    'city_ibge_code': 'codIbge',
    'date': 'data',
    'epidemiological_week':'semEpid',
    'estimated_population':'popEstim',
    'last_available_confirmed':'confAcc',
    'last_available_confirmed_per_100k_inhabitants':'confAcc100k',
    'last_available_deaths':'obitoAcc',
    'place_type':'tipoLocal',
    'state':'uf',
    'new_confirmed':'confDia',
    'new_deaths':'obitoDia' 
})

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3477376 entries, 0 to 3477375
Data columns (total 12 columns):
 #   Column       Dtype
---  ------       -----
 0   muni         object
 1   codIbge      float64
 2   data         object
 3   semEpid      int64
 4   popEstim     float64
 5   confAcc      int64
 6   confAcc100k  float64
 7   obitoAcc     int64
 8   tipoLocal    object
 9   uf           object
 10  confDia      int64
 11  obitoDia     int64
dtypes: float64(3), int64(5), object(4)
memory usage: 318.4+ MB

In [9]:
dataset.dropna(subset=['muni', 'codIbge'], inplace= True)

In [10]:
print(dataset[0:15])

          muni    codIbge        data  semEpid  popEstim  confAcc  \
0   Rio Branco  1200401.0  2020-03-17   202012  413418.0        3
2   Rio Branco  1200401.0  2020-03-18   202012  413418.0        3
4   Rio Branco  1200401.0  2020-03-19   202012  413418.0        4
6   Rio Branco  1200401.0  2020-03-20   202012  413418.0        7
8   Rio Branco  1200401.0  2020-03-21   202012  413418.0       11
10  Rio Branco  1200401.0  2020-03-22   202013  413418.0       11
12  Rio Branco  1200401.0  2020-03-23   202013  413418.0       17
14  Rio Branco  1200401.0  2020-03-24   202013  413418.0       21
16  Rio Branco  1200401.0  2020-03-25   202013  413418.0       23
18  Rio Branco  1200401.0  2020-03-26   202013  413418.0       23
20  Rio Branco  1200401.0  2020-03-27   202013  413418.0       25
22  Rio Branco  1200401.0  2020-03-28   202013  413418.0       25
24  Acrelândia  1200013.0  2020-03-29   202014   15490.0        2
25  Porto Acre  1200807.0  2020-03-29   202014   18824.0        1
26  Rio Branco  1200401.0  2020-03-29   202014  413418.0       31

    confAcc100k  obitoAcc tipoLocal  uf  confDia  obitoDia
0       0.72566         0      city  AC        3         0
2       0.72566         0      city  AC        0         0
4       0.96754         0      city  AC        1         0
6       1.69320         0      city  AC        3         0
8       2.66075         0      city  AC        4         0
10      2.66075         0      city  AC        0         0
12      4.11206         0      city  AC        6         0
14      5.07960         0      city  AC        4         0
16      5.56338         0      city  AC        2         0
18      5.56338         0      city  AC        0         0
20      6.04715         0      city  AC        2         0
22      6.04715         0      city  AC        0         0
24     12.91156         0      city  AC        2         0
25      5.31237         0      city  AC        1         0
26      7.49846         0      city  AC        6         0

In [11]:
dataset.head()

,muni,codIbge,data,semEpid,popEstim,confAcc,confAcc100k,obitoAcc,tipoLocal,uf,confDia,obitoDia
0,Rio Branco,1200401.0,2020-03-17,202012,413418.0,3,0.72566,0,city,AC,3,0
2,Rio Branco,1200401.0,2020-03-18,202012,413418.0,3,0.72566,0,city,AC,0,0
4,Rio Branco,1200401.0,2020-03-19,202012,413418.0,4,0.96754,0,city,AC,1,0
6,Rio Branco,1200401.0,2020-03-20,202012,413418.0,7,1.69320,0,city,AC,3,0
8,Rio Branco,1200401.0,2020-03-21,202012,413418.0,11,2.66075,0,city,AC,4,0

In [12]:
aggregation = {
   'muni':        'first',
   'codIbge':     'first',
   'data':        'last',
   'semEpid':     'first',
   'popEstim':    'max',
   'confAcc':     'max',
   'confAcc100k': 'max',
   'obitoAcc':    'max',
   'tipoLocal':   'first',
   'uf':          'first',
   'confDia':     'sum',
   'obitoDia':    'sum'
}
dataset = dataset.groupby(["semEpid", "codIbge"]).aggregate(aggregation).reindex(columns = dataset.columns)

In [13]:
dataset.head()

                                  muni    codIbge        data  semEpid  \
semEpid codIbge
202009  3550308.0            São Paulo  3550308.0  2020-02-29   202009
202010  2910800.0     Feira de Santana  2910800.0  2020-03-07   202010
        3300407.0          Barra Mansa  3300407.0  2020-03-07   202010
        3304557.0       Rio de Janeiro  3304557.0  2020-03-07   202010
        3547304.0  Santana de Parnaíba  3547304.0  2020-03-07   202010

                     popEstim  confAcc  confAcc100k  obitoAcc tipoLocal  uf  \
semEpid codIbge
202009  3550308.0  12325232.0        2      0.01623         0      city  SP
202010  2910800.0    619609.0        2      0.32278         0      city  BA
        3300407.0    184833.0        1      0.54103         0      city  RJ
        3304557.0   6747815.0        1      0.01482         0      city  RJ
        3547304.0    142301.0        1      0.70274         0      city  SP

                   confDia  obitoDia
semEpid codIbge
202009  3550308.0        2         0
202010  2910800.0        2         0
        3300407.0        1         0
        3304557.0        1         0
        3547304.0        1         0

In [14]:
 dataset.reset_index(drop= True, inplace = True)

In [15]:
dataset.head()

,muni,codIbge,data,semEpid,popEstim,confAcc,confAcc100k,obitoAcc,tipoLocal,uf,confDia,obitoDia
0,São Paulo,3550308.0,2020-02-29,202009,12325232.0,2,0.01623,0,city,SP,2,0
1,Feira de Santana,2910800.0,2020-03-07,202010,619609.0,2,0.32278,0,city,BA,2,0
2,Barra Mansa,3300407.0,2020-03-07,202010,184833.0,1,0.54103,0,city,RJ,1,0
3,Rio de Janeiro,3304557.0,2020-03-07,202010,6747815.0,1,0.01482,0,city,RJ,1,0
4,Santana de Parnaíba,3547304.0,2020-03-07,202010,142301.0,1,0.70274,0,city,SP,1,0

In [16]:
print(dataset.shape[0])

497415

In [17]:
if not os.path.exists('covid_dataset.csv'):
    colNames = ['muni', 'codIbge', 'uf', 'lat', 'lon']
    geoloc = pd.DataFrame(columns = colNames)
    geoloc.to_csv('covid_dataset.csv', encoding = 'utf-8')

In [18]:
covid_dataset = pd.read_csv('covid_dataset.csv')
covid_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  0 non-null      object
 1   muni        0 non-null      object
 2   codIbge     0 non-null      object
 3   uf          0 non-null      object
 4   lat         0 non-null      object
 5   lon         0 non-null      object
dtypes: object(6)
memory usage: 0.0+ bytes

In [19]:
covid_dataset.head()

Empty DataFrame
Columns: [Unnamed: 0, muni, codIbge, uf, lat, lon]
Index: []

In [20]:
geoloc = pd.read_csv('covid_dataset.csv', encoding = 'utf-8', usecols=['muni', 'codIbge', 'uf', 'lat', 'lon'])

In [21]:
print(geoloc.head(15))

Empty DataFrame
Columns: [muni, codIbge, uf, lat, lon]
Index: []

In [22]:
joinDataset = pd.merge(dataset, geoloc, on = ['muni', 'codIbge', 'uf'], how = 'left', indicator = True)

In [23]:
joinDataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 497415 entries, 0 to 497414
Data columns (total 15 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   muni         497415 non-null  object
 1   codIbge      497415 non-null  float64
 2   data         497415 non-null  object
 3   semEpid      497415 non-null  int64
 4   popEstim     497415 non-null  float64
 5   confAcc      497415 non-null  int64
 6   confAcc100k  495476 non-null  float64
 7   obitoAcc     497415 non-null  int64
 8   tipoLocal    497415 non-null  object
 9   uf           497415 non-null  object
 10  confDia      497415 non-null  int64
 11  obitoDia     497415 non-null  int64
 12  lat          0 non-null       object
 13  lon          0 non-null       object
 14  _merge       497415 non-null  category
dtypes: category(1), float64(3), int64(5), object(6)
memory usage: 57.4+ MB

In [24]:
joinDataset.head()

,muni,codIbge,data,semEpid,popEstim,confAcc,confAcc100k,obitoAcc,tipoLocal,uf,confDia,obitoDia,lat,lon,_merge
0,São Paulo,3550308.0,2020-02-29,202009,12325232.0,2,0.01623,0,city,SP,2,0,NaN,NaN,left_only
1,Feira de Santana,2910800.0,2020-03-07,202010,619609.0,2,0.32278,0,city,BA,2,0,NaN,NaN,left_only
2,Barra Mansa,3300407.0,2020-03-07,202010,184833.0,1,0.54103,0,city,RJ,1,0,NaN,NaN,left_only
3,Rio de Janeiro,3304557.0,2020-03-07,202010,6747815.0,1,0.01482,0,city,RJ,1,0,NaN,NaN,left_only
4,Santana de Parnaíba,3547304.0,2020-03-07,202010,142301.0,1,0.70274,0,city,SP,1,0,NaN,NaN,left_only

In [25]:
print(joinDataset.head(15))

                   muni    codIbge        data  semEpid    popEstim  confAcc  \
0             São Paulo  3550308.0  2020-02-29   202009  12325232.0        2
1      Feira de Santana  2910800.0  2020-03-07   202010    619609.0        2
2           Barra Mansa  3300407.0  2020-03-07   202010    184833.0        1
3        Rio de Janeiro  3304557.0  2020-03-07   202010   6747815.0        1
4   Santana de Parnaíba  3547304.0  2020-03-07   202010    142301.0        1
5             São Paulo  3550308.0  2020-03-07   202010  12325232.0       12
6              Brasília  5300108.0  2020-03-07   202010   3055149.0        1
7                Manaus  1302603.0  2020-03-14   202011   2219580.0        2
8                 Natal  2408102.0  2020-03-14   202011    890480.0        1
9                Recife  2611606.0  2020-03-14   202011   1653461.0        6
10               Maceió  2704302.0  2020-03-14   202011   1025360.0        1
11              Aracaju  2800308.0  2020-03-14   202011    664908.0        1
12     Feira de Santana  2910800.0  2020-03-14   202011    619609.0        4
13             Salvador  2927408.0  2020-03-14   202011   2886698.0        3
14          Divinópolis  3122306.0  2020-03-14   202011    240408.0        1

    confAcc100k  obitoAcc tipoLocal  uf  confDia  obitoDia  lat  lon  \
0       0.01623         0      city  SP        2         0  NaN  NaN
1       0.32278         0      city  BA        2         0  NaN  NaN
2       0.54103         0      city  RJ        1         0  NaN  NaN
3       0.01482         0      city  RJ        1         0  NaN  NaN
4       0.70274         0      city  SP        1         0  NaN  NaN
5       0.09736         0      city  SP       10         0  NaN  NaN
6       0.03273         0      city  DF        1         0  NaN  NaN
7       0.09011         0      city  AM        2         0  NaN  NaN
8       0.11230         0      city  RN        1         0  NaN  NaN
9       0.36288         0      city  PE        6         0  NaN  NaN
10      0.09753         0      city  AL        1         0  NaN  NaN
11      0.15040         0      city  SE        1         0  NaN  NaN
12      0.64557         0      city  BA        2         0  NaN  NaN
13      0.10392         0      city  BA        3         0  NaN  NaN
14      0.41596         0      city  MG        1         0  NaN  NaN

       _merge
0   left_only
1   left_only
2   left_only
3   left_only
4   left_only
5   left_only
6   left_only
7   left_only
8   left_only
9   left_only
10  left_only
11  left_only
12  left_only
13  left_only
14  left_only

In [26]:
print(joinDataset.loc[joinDataset['_merge']=='left_only'])

                       muni    codIbge        data  semEpid    popEstim  \
0                 São Paulo  3550308.0  2020-02-29   202009  12325232.0
1          Feira de Santana  2910800.0  2020-03-07   202010    619609.0
2               Barra Mansa  3300407.0  2020-03-07   202010    184833.0
3            Rio de Janeiro  3304557.0  2020-03-07   202010   6747815.0
4       Santana de Parnaíba  3547304.0  2020-03-07   202010    142301.0
...                     ...        ...         ...      ...         ...
497410           Vianópolis  5222005.0  2022-01-19   202203     13977.0
497411       Vicentinópolis  5222054.0  2022-01-19   202203      8873.0
497412             Vila Boa  5222203.0  2022-01-19   202203      6312.0
497413        Vila Propício  5222302.0  2022-01-19   202203      5882.0
497414             Brasília  5300108.0  2022-01-19   202203   3055149.0

        confAcc  confAcc100k  obitoAcc tipoLocal  uf  confDia  obitoDia  lat  \
0             2      0.01623         0      city  SP        2         0  NaN
1             2      0.32278         0      city  BA        2         0  NaN
2             1      0.54103         0      city  RJ        1         0  NaN
3             1      0.01482         0      city  RJ        1         0  NaN
4             1      0.70274         0      city  SP        1         0  NaN
...         ...          ...       ...       ...  ..      ...       ...  ...
497410     1248   8928.95471        35      city  GO        0         0  NaN
497411     1456  16409.33168        24      city  GO        0         0  NaN
497412      232   3675.53866         4      city  GO        0         0  NaN
497413      415   7055.42333         8      city  GO        0         0  NaN
497414   470565  15402.35844     10163      city  DF        0         0  NaN

        lon     _merge
0       NaN  left_only
1       NaN  left_only
2       NaN  left_only
3       NaN  left_only
4       NaN  left_only
...     ...        ...
497410  NaN  left_only
497411  NaN  left_only
497412  NaN  left_only
497413  NaN  left_only
497414  NaN  left_only

[497415 rows x 15 columns]

In [27]:
print(joinDataset.shape[0])

497415

In [28]:
joinDataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 497415 entries, 0 to 497414
Data columns (total 15 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   muni         497415 non-null  object
 1   codIbge      497415 non-null  float64
 2   data         497415 non-null  object
 3   semEpid      497415 non-null  int64
 4   popEstim     497415 non-null  float64
 5   confAcc      497415 non-null  int64
 6   confAcc100k  495476 non-null  float64
 7   obitoAcc     497415 non-null  int64
 8   tipoLocal    497415 non-null  object
 9   uf           497415 non-null  object
 10  confDia      497415 non-null  int64
 11  obitoDia     497415 non-null  int64
 12  lat          0 non-null       object
 13  lon          0 non-null       object
 14  _merge       497415 non-null  category
dtypes: category(1), float64(3), int64(5), object(6)
memory usage: 57.4+ MB

In [29]:
print(joinDataset[875:885])

                        muni    codIbge        data  semEpid  popEstim  \
875              Mandirituba  4114302.0  2020-04-04   202014   27315.0
876  Marechal Cândido Rondon  4114609.0  2020-04-04   202014   53495.0
877                  Maringá  4115200.0  2020-04-04   202014  430157.0
878               Mariópolis  4115309.0  2020-04-04   202014    6632.0
879                 Matinhos  4115705.0  2020-04-04   202014   35219.0
880               Medianeira  4115804.0  2020-04-04   202014   46574.0
881                   Palmas  4117602.0  2020-04-04   202014   51755.0
882                 Palmeira  4117701.0  2020-04-04   202014   33994.0
883                Paranaguá  4118204.0  2020-04-04   202014  156174.0
884                Paranavaí  4118402.0  2020-04-04   202014   88922.0

     confAcc  confAcc100k  obitoAcc tipoLocal  uf  confDia  obitoDia  lat  \
875        1      3.66099         0      city  PR        1         0  NaN
876        2      3.73867         0      city  PR        2         0  NaN
877       19      4.41699         2      city  PR       12         0  NaN
878        1     15.07841         0      city  PR        0         0  NaN
879        2      5.67875         0      city  PR        2         0  NaN
880        3      6.44136         0      city  PR        3         0  NaN
881        1      1.93218         0      city  PR        1         0  NaN
882        2      5.88339         0      city  PR        2         0  NaN
883        4      2.56125         0      city  PR        4         0  NaN
884        3      3.37374         0      city  PR        1         0  NaN

     lon     _merge
875  NaN  left_only
876  NaN  left_only
877  NaN  left_only
878  NaN  left_only
879  NaN  left_only
880  NaN  left_only
881  NaN  left_only
882  NaN  left_only
883  NaN  left_only
884  NaN  left_only

In [31]:
getgeo = []
for index, rows in joinDataset.iterrows():
    if (rows._merge == 'left_only') and ([rows.muni, rows.codIbge, rows.uf] not in getgeo):
        getgeo.append([rows.muni, rows.codIbge, rows.uf])
        query = (str(rows.muni.lower()) + ', ' + str(rows.uf.lower()) + ', ' + 'brasil')
        geocoder = OpenCageGeocode(key)
        coord = geocoder.geocode(query)
        geoloc = geoloc.append(pd.Series([
            rows.muni,
            rows.codIbge,
            rows.uf,
            coord[0]['geometry']['lat'],
            coord[0]['geometry']['lng']], index = geoloc.columns), ignore_index = True)
        print('Municipio adicionado: ', rows.muni, rows.codIbge, rows.uf, coord[0]['geometry']['lat'], coord[0]['geometry']['lng'])
        joinDataset['lat'] = coord[0]['geometry']['lat']
        joinDataset['lon'] = coord[0]['geometry']['lng']

RateLimitExceededError: Your rate limit has expired. It will reset to 2500 on 2022-01-24T00:00:00

In [32]:
print(len(getgeo))

1

In [33]:
print(joinDataset.head(15))

                   muni    codIbge        data  semEpid    popEstim  confAcc  \
0             São Paulo  3550308.0  2020-02-29   202009  12325232.0        2
1      Feira de Santana  2910800.0  2020-03-07   202010    619609.0        2
2           Barra Mansa  3300407.0  2020-03-07   202010    184833.0        1
3        Rio de Janeiro  3304557.0  2020-03-07   202010   6747815.0        1
4   Santana de Parnaíba  3547304.0  2020-03-07   202010    142301.0        1
5             São Paulo  3550308.0  2020-03-07   202010  12325232.0       12
6              Brasília  5300108.0  2020-03-07   202010   3055149.0        1
7                Manaus  1302603.0  2020-03-14   202011   2219580.0        2
8                 Natal  2408102.0  2020-03-14   202011    890480.0        1
9                Recife  2611606.0  2020-03-14   202011   1653461.0        6
10               Maceió  2704302.0  2020-03-14   202011   1025360.0        1
11              Aracaju  2800308.0  2020-03-14   202011    664908.0        1
12     Feira de Santana  2910800.0  2020-03-14   202011    619609.0        4
13             Salvador  2927408.0  2020-03-14   202011   2886698.0        3
14          Divinópolis  3122306.0  2020-03-14   202011    240408.0        1

    confAcc100k  obitoAcc tipoLocal  uf  confDia  obitoDia  lat  lon  \
0       0.01623         0      city  SP        2         0  NaN  NaN
1       0.32278         0      city  BA        2         0  NaN  NaN
2       0.54103         0      city  RJ        1         0  NaN  NaN
3       0.01482         0      city  RJ        1         0  NaN  NaN
4       0.70274         0      city  SP        1         0  NaN  NaN
5       0.09736         0      city  SP       10         0  NaN  NaN
6       0.03273         0      city  DF        1         0  NaN  NaN
7       0.09011         0      city  AM        2         0  NaN  NaN
8       0.11230         0      city  RN        1         0  NaN  NaN
9       0.36288         0      city  PE        6         0  NaN  NaN
10      0.09753         0      city  AL        1         0  NaN  NaN
11      0.15040         0      city  SE        1         0  NaN  NaN
12      0.64557         0      city  BA        2         0  NaN  NaN
13      0.10392         0      city  BA        3         0  NaN  NaN
14      0.41596         0      city  MG        1         0  NaN  NaN

       _merge
0   left_only
1   left_only
2   left_only
3   left_only
4   left_only
5   left_only
6   left_only
7   left_only
8   left_only
9   left_only
10  left_only
11  left_only
12  left_only
13  left_only
14  left_only

In [34]:
print(joinDataset[875:885])

                        muni    codIbge        data  semEpid  popEstim  \
875              Mandirituba  4114302.0  2020-04-04   202014   27315.0
876  Marechal Cândido Rondon  4114609.0  2020-04-04   202014   53495.0
877                  Maringá  4115200.0  2020-04-04   202014  430157.0
878               Mariópolis  4115309.0  2020-04-04   202014    6632.0
879                 Matinhos  4115705.0  2020-04-04   202014   35219.0
880               Medianeira  4115804.0  2020-04-04   202014   46574.0
881                   Palmas  4117602.0  2020-04-04   202014   51755.0
882                 Palmeira  4117701.0  2020-04-04   202014   33994.0
883                Paranaguá  4118204.0  2020-04-04   202014  156174.0
884                Paranavaí  4118402.0  2020-04-04   202014   88922.0

     confAcc  confAcc100k  obitoAcc tipoLocal  uf  confDia  obitoDia  lat  \
875        1      3.66099         0      city  PR        1         0  NaN
876        2      3.73867         0      city  PR        2         0  NaN
877       19      4.41699         2      city  PR       12         0  NaN
878        1     15.07841         0      city  PR        0         0  NaN
879        2      5.67875         0      city  PR        2         0  NaN
880        3      6.44136         0      city  PR        3         0  NaN
881        1      1.93218         0      city  PR        1         0  NaN
882        2      5.88339         0      city  PR        2         0  NaN
883        4      2.56125         0      city  PR        4         0  NaN
884        3      3.37374         0      city  PR        1         0  NaN

     lon     _merge
875  NaN  left_only
876  NaN  left_only
877  NaN  left_only
878  NaN  left_only
879  NaN  left_only
880  NaN  left_only
881  NaN  left_only
882  NaN  left_only
883  NaN  left_only
884  NaN  left_only

In [35]:
if len(getgeo) > 0:
    geoloc.to_csv('covid_dataset.csv', encoding='utf-8')

In [36]:
print(geoloc)

Empty DataFrame
Columns: [muni, codIbge, uf, lat, lon]
Index: []

In [37]:
print(getgeo)

[['São Paulo', 3550308.0, 'SP']]

In [38]:
joinDataset.to_csv('covid_dataset.csv', encoding = 'utf-8')

In [39]:
joinDataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 497415 entries, 0 to 497414
Data columns (total 15 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   muni         497415 non-null  object
 1   codIbge      497415 non-null  float64
 2   data         497415 non-null  object
 3   semEpid      497415 non-null  int64
 4   popEstim     497415 non-null  float64
 5   confAcc      497415 non-null  int64
 6   confAcc100k  495476 non-null  float64
 7   obitoAcc     497415 non-null  int64
 8   tipoLocal    497415 non-null  object
 9   uf           497415 non-null  object
 10  confDia      497415 non-null  int64
 11  obitoDia     497415 non-null  int64
 12  lat          0 non-null       object
 13  lon          0 non-null       object
 14  _merge       497415 non-null  category
dtypes: category(1), float64(3), int64(5), object(6)
memory usage: 57.4+ MB

In [40]:
joinDataset.head(15)

,muni,codIbge,data,semEpid,popEstim,confAcc,confAcc100k,obitoAcc,tipoLocal,uf,confDia,obitoDia,lat,lon,_merge
0,São Paulo,3550308.0,2020-02-29,202009,12325232.0,2,0.01623,0,city,SP,2,0,NaN,NaN,left_only
1,Feira de Santana,2910800.0,2020-03-07,202010,619609.0,2,0.32278,0,city,BA,2,0,NaN,NaN,left_only
2,Barra Mansa,3300407.0,2020-03-07,202010,184833.0,1,0.54103,0,city,RJ,1,0,NaN,NaN,left_only
3,Rio de Janeiro,3304557.0,2020-03-07,202010,6747815.0,1,0.01482,0,city,RJ,1,0,NaN,NaN,left_only
4,Santana de Parnaíba,3547304.0,2020-03-07,202010,142301.0,1,0.70274,0,city,SP,1,0,NaN,NaN,left_only
5,São Paulo,3550308.0,2020-03-07,202010,12325232.0,12,0.09736,0,city,SP,10,0,NaN,NaN,left_only
6,Brasília,5300108.0,2020-03-07,202010,3055149.0,1,0.03273,0,city,DF,1,0,NaN,NaN,left_only
7,Manaus,1302603.0,2020-03-14,202011,2219580.0,2,0.09011,0,city,AM,2,0,NaN,NaN,left_only
8,Natal,2408102.0,2020-03-14,202011,890480.0,1,0.11230,0,city,RN,1,0,NaN,NaN,left_only
9,Recife,2611606.0,2020-03-14,202011,1653461.0,6,0.36288,0,city,PE,6,0,NaN,NaN,left_only
10,Maceió,2704302.0,2020-03-14,202011,1025360.0,1,0.09753,0,city,AL,1,0,NaN,NaN,left_only
11,Aracaju,2800308.0,2020-03-14,202011,664908.0,1,0.15040,0,city,SE,1,0,NaN,NaN,left_only
12,Feira de Santana,2910800.0,2020-03-14,202011,619609.0,4,0.64557,0,city,BA,2,0,NaN,NaN,left_only
13,Salvador,2927408.0,2020-03-14,202011,2886698.0,3,0.10392,0,city,BA,3,0,NaN,NaN,left_only
14,Divinópolis,3122306.0,2020-03-14,202011,240408.0,1,0.41596,0,city,MG,1,0,NaN,NaN,left_only